// packages/frontend/src/lib/Footer.svelte
<script>
  // import SocialLinks from './SocialLinks.svelte';
</script>

<footer class="offset bg-gray-50 dark:bg-dark-800">
  <div class="max-w-7xl mx-auto py-12 px-4 overflow-hidden sm:px-6 lg:px-8">
    <nav class="-mx-5 -my-2 flex flex-wrap justify-center" aria-label="Footer">
      <div class="px-5 py-2">
        <a
          title="Link"
          href="#"
          class="text-base text-gray-500 hover:text-gray-900"
          rel="preload"
        >
          link1
        </a>
      </div>

      <div class="px-5 py-2">
        <a
          title="Link"
          href="#"
          class="text-base text-gray-500 hover:text-gray-900"
          rel="preload"
        >
          link1
        </a>
      </div>

      <div class="px-5 py-2">
        <a
          title="Link"
          href="#"
          class="text-base text-gray-500 hover:text-gray-900"
          rel="preload"
        >
          link1
        </a>
      </div>

      <div class="px-5 py-2">
        <a
          title="Link"
          href="#"
          class="text-base text-gray-500 hover:text-gray-900"
          rel="preload"
        >
          link1
        </a>
      </div>
    </nav>
    <div class="mt-8 flex justify-center space-x-6">
      <!-- <SocialLinks /> -->
    </div>

    <p class="mt-8 text-center text-xs text-gray-400">
      Designed and coded (with love) &copy; {new Date().getFullYear()} Aaron Leopold.
      All rights reserved
    </p>
  </div>
</footer>

<style>
  .offset {
    margin-top: 5.5rem;
  }
</style>

// packages/frontend/src/app/components/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: [],
})
export class FooterComponent implements OnInit {
  year: number = new Date().getFullYear();

  constructor() {}

  ngOnInit(): void {}
}

<footer class="min-h-16 offset bg-gray-100 dark:bg-dark-800">
  <div class="max-w-7xl mx-auto py-12 px-4 overflow-hidden sm:px-6 lg:px-8">
    <nav class="-mx-5 -my-2 flex flex-wrap justify-center" aria-label="Footer">
      <div class="px-5 py-2">
        <a
          title="Link"
          href="#"
          class="text-base text-gray-500 hover:text-gray-900"
          rel="preload"
        >
          link1
        </a>
      </div>

      <div class="px-5 py-2">
        <a
          title="Link"
          href="#"
          class="text-base text-gray-500 hover:text-gray-900"
          rel="preload"
        >
          link1
        </a>
      </div>

      <div class="px-5 py-2">
        <a
          title="Link"
          href="#"
          class="text-base text-gray-500 hover:text-gray-900"
          rel="preload"
        >
          link1
        </a>
      </div>

      <div class="px-5 py-2">
        <a
          title="Link"
          href="#"
          class="text-base text-gray-500 hover:text-gray-900"
          rel="preload"
        >
          link1
        </a>
      </div>
    </nav>
    <div class="mt-8 flex justify-center space-x-6">
      <!-- <SocialLinks /> -->
    </div>

    <p class="mt-8 text-center text-xs text-gray-400">
      Designed and coded (with love) &copy; {{ year }} Aaron Leopold. All rights
      reserved
    </p>
  </div>
</footer>
